# Generated by Django 4.2 on 2023-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0004_alter_artist_genres_alter_venue_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='seeking_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='seeking_description',
            field=models.TextField(null=True),
        ),
    ]
